"""Central Romanian interface text."""

APP_NAME = "TataTuya"
REFRESH = "Actualizează"
SETTINGS = "Setări"
METER = "Contor"
STATE = "Stare"
CURRENT_READING = "Index curent"
LAST_READING = "Ultima citire"
ACTIONS = "Acțiuni"
CALCULATE = "Calculează"
HISTORY = "Istoric"
INFO = "Info"
STATUS = "Status"

READY = "Pregătit"
LOADING_LOCAL_DATA = "Se încarcă datele locale…"
LOADING_LOCAL_TITLE = "Se încarcă datele salvate"
LOADING_LOCAL_HELP = "Așteptați cât timp pregătim contoarele și setările aplicației."
LOCAL_DATA_FAILED = "Încărcarea datelor locale nu a reușit"
LOCAL_DATA_ERROR_TITLE = "Datele locale nu sunt disponibile"
LOCAL_DATA_ERROR_HELP = (
    "Verificați dacă aplicația poate accesa spațiul de stocare, apoi încercați din nou."
)
RETRY = "Reîncearcă"
REFRESHING = "Se actualizează contoarele…"
REFRESH_COMPLETE = "Actualizare finalizată"
REFRESH_PARTIAL = "Actualizare parțială"
REFRESH_FAILED = "Actualizarea nu a reușit"
NO_METERS = "Nu există contoare disponibile."
NO_METERS_HELP = "Apăsați Actualizează pentru a încărca dispozitivele din Tuya."
SETTINGS_REQUIRED = "Configurați conexiunea Tuya"
SETTINGS_REQUIRED_HELP = (
    "Introduceți Client ID, Client Secret, Account UID și regiunea în Setări."
)
OPEN_SETTINGS = "Deschide Setări"
UNKNOWN = "Necunoscută"
ONLINE = "Online"
OFFLINE = "Offline"
NO_READING = "Fără citire"
CLOSING_AFTER_WORK = "Se finalizează operațiunea înainte de închidere…"
METERS_COUNT = "{count} contoare"
ONE_METER = "1 contor"
