"""Central Romanian interface text."""

APP_NAME = "TataTuya"
REFRESH = "Actualizează"
SETTINGS = "Setări"
METER = "Contor"
STATE = "Stare"
CURRENT_READING = "Index curent"
LAST_READING = "Ultima citire"
ACTIONS = "Acțiuni"
CALCULATE = "Calculează"
HISTORY = "Istoric"
INFO = "Info"
STATUS = "Status"

READY = "Pregătit"
LOADING_LOCAL_DATA = "Se încarcă datele locale…"
LOADING_LOCAL_TITLE = "Se încarcă datele salvate"
LOADING_LOCAL_HELP = "Așteptați cât timp pregătim contoarele și setările aplicației."
LOCAL_DATA_FAILED = "Încărcarea datelor locale nu a reușit"
LOCAL_DATA_ERROR_TITLE = "Datele locale nu sunt disponibile"
LOCAL_DATA_ERROR_HELP = (
    "Verificați dacă aplicația poate accesa spațiul de stocare, apoi încercați din nou."
)
RETRY = "Reîncearcă"
REFRESHING = "Se actualizează contoarele…"
REFRESH_COMPLETE = "Actualizare finalizată"
REFRESH_PARTIAL = "Actualizare parțială"
REFRESH_FAILED = "Actualizarea nu a reușit"
NO_METERS = "Nu există contoare disponibile."
NO_METERS_HELP = "Apăsați Actualizează pentru a încărca dispozitivele din Tuya."
SETTINGS_REQUIRED = "Configurați conexiunea Tuya"
SETTINGS_REQUIRED_HELP = (
    "Introduceți Client ID, Client Secret și regiunea în Setări."
)
OPEN_SETTINGS = "Deschide Setări"
UNKNOWN = "Necunoscută"
ONLINE = "Online"
OFFLINE = "Offline"
NOT_IN_TUYA = "Indisponibil în Tuya"
STATUS_UNAVAILABLE = "Statusul nu este disponibil deoarece contorul nu mai apare în Tuya."
NO_READING = "Fără citire"
CLOSING_AFTER_WORK = "Se finalizează operațiunea înainte de închidere…"
METERS_COUNT = "{count} contoare"
ONE_METER = "1 contor"

SETTINGS_SUBTITLE = (
    "Configurați accesul numai pentru citire la Tuya și moneda folosită pentru calcule."
)
SETTINGS_NOT_TESTED = "Conexiunea nu a fost testată în această sesiune."
SETTINGS_CHANGED_AFTER_TEST = "Datele s-au schimbat. Testați din nou conexiunea."
TEST_CONNECTION = "Testează conexiunea"
TESTING_CONNECTION = "Se testează conexiunea Tuya…"
CONNECTION_SUCCEEDED = "Conexiune reușită. {count} dispozitive Tuya asociate."
CONNECTION_SUCCEEDED_ONE = "Conexiune reușită. 1 dispozitiv Tuya asociat."
CONNECTION_FAILED = "Conexiunea nu a putut fi verificată."
SETTINGS_SAVED_VERIFIED = "Setări salvate și conexiune verificată"
SETTINGS_SAVED_UNVERIFIED = "Setări salvate; conexiune neverificată"
SAVE = "Salvează"
SAVING_SETTINGS = "Se salvează setările…"
SETTINGS_SAVE_FAILED = "Setările nu au putut fi salvate."
CLOSE = "Închide"
SHOW_TECHNICAL_DETAILS = "Arată detaliile tehnice"
HIDE_TECHNICAL_DETAILS = "Ascunde detaliile tehnice"
COPY_TECHNICAL_DETAILS = "Copiază detaliile"

CALCULATION_TITLE = "Calcul consum"
CALCULATION_SUBTITLE = "Alegeți două citiri salvate pentru acest contor."
START_READING = "Citire inițială"
END_READING = "Citire finală"
START_VALUE = "Index inițial"
END_VALUE = "Index final"
CONSUMPTION = "Consum"
PRICE_PER_KWH = "Preț per kWh"
CURRENCY = "Monedă"
TOTAL = "Total"
PRICE_EXAMPLE = "de exemplu 0,80"
PREVIOUS_PRICE = "Ultimul preț: {price} {currency}"
PRICE_REQUIRED_FOR_TOTAL = "Introduceți un preț pentru a vedea totalul."
CALCULATION_INVALID_PREVIEW = "Verificați citirile și prețul selectate."
SAVE_CALCULATION = "Salvează calculul"
PREPARING_CALCULATION = "Se pregătesc citirile pentru calcul…"
SAVING_CALCULATION = "Se salvează calculul…"

HISTORY_TITLE = "Istoric contor"
READINGS = "Citiri"
CALCULATIONS = "Calcule"
DATE_AND_TIME = "Data și ora"
CUMULATIVE_READING = "Index cumulativ"
RAW_VALUE = "Valoare brută"
SCALE_AND_UNIT = "Scară și unitate"
SOURCE = "Sursă"
SOURCE_BATCH = "Actualizare"
SOURCE_INDIVIDUAL = "Status individual"
CALCULATION_DATE = "Data calculului"
PERIOD = "Perioadă"
UNIT_PRICE = "Preț unitar"
NO_READING_HISTORY = "Nu există încă citiri salvate pentru acest contor."
NO_CALCULATION_HISTORY = "Nu există încă calcule salvate pentru acest contor."
PREPARING_HISTORY = "Se încarcă istoricul contorului…"
LOADING_SETTINGS = "Se încarcă setările…"

DEVICE_INFO_TITLE = "Informații contor"
DEVICE_INFO_SUBTITLE = "Metadate primite de la Tuya. Aceste informații nu pot fi modificate aici."
DEVICE_NAME = "Nume contor"
DEVICE_ID = "ID dispozitiv"
PRODUCT = "Produs"
PRODUCT_ID = "ID produs"
CATEGORY = "Categorie Tuya"
ENERGY_DATA_POINT = "Cod energie cumulată"
ENERGY_UNIT = "Unitate energie"
ENERGY_SCALE = "Scară energie"
FIRST_SEEN = "Prima detectare"
LAST_SEEN = "Ultima detectare"
NOT_AVAILABLE = "Indisponibil"

DEVICE_STATUS_TITLE = "Status contor"
STATUS_VALUES = "Valori returnate de Tuya"
TUYA_CODE = "Cod Tuya"
TUYA_VALUE = "Valoare brută"
RAW_TUYA_RESPONSE = "Răspuns Tuya brut"
NO_STATUS_VALUES = "Tuya nu a returnat valori de status pentru acest contor."
STATUS_READING_SAVED = "Citire salvată din acest status: {reading}."
STATUS_READING_NOT_SAVED = "Citirea nu a fost salvată. {message}"
STATUS_WITHOUT_READING = "Statusul nu a conținut o citire de energie utilizabilă."
LOADING_STATUS = "Se încarcă statusul contorului…"
